FROM python:3.9.5-slim-buster

RUN apt update \
    && apt install netcat -y \
    && apt clean

RUN pip install --upgrade pip

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY requirements requirements
RUN pip install -r requirements/ci.txt

COPY . .

RUN adduser --disabled-password user
USER user
