version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@postgres:5432/test
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
