name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE }}:latest

  test:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      packages: read

    env:
        WORKDIR: /usr/src/app

    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        PORT: 5000
        DATABASE_TEST_URL: postgresql://postgres:postgres@postgres:5432/users
      ports:
        - 5000:5000

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: users
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Lint
        working-directory: ${{ env.WORKDIR }}
        run:  |
          flake8 src
          black src --check
          isort src --check-only
      - name: Test
        working-directory: ${{ env.WORKDIR }}
        run: pytest -p no:warnings

  deploy:
    needs: test

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      REGISTRY: registry.heroku.com
      HEROKU_APP: floating-stream-79447
      HEROKU_IMAGE: registry.heroku.com/floating-stream-79447/web
      WORKDIR: /usr/src/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Heroku container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.HEROKU_AUTH_TOKEN }}

      - name: Build and push image to Heroku
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.prod
          push: true
          tags: ${{ env.HEROKU_IMAGE }}

      - name: Create new release
        working-directory: ${{ env.WORKDIR }}
        run: |
          chmod +x ./scripts/release.sh
          ./scripts/release.sh
